### ISSUE TITLE
Electron 11's disable-site-isolation-trials breaks Logger

### ISSUE THREAD

**Issue by p-try** [jitsi/jitsi-meet-logger#8]
When enabling disable-site-isolation-trials in Electron 11.0.1, Logger breaks with the error message
`Uncaught TypeError: Cannot read property 'indexOf' of undefined`
on line 102.

I don't know why this only happens when site isolation is disabled, but the reason for the error is that `stack.length` is < 3, which causes `stack[2]` to be undefined.

The result is that Jitsi will not load.

**Comment by p-try** [comment]
Pull request: #9

**Comment by sergeyd63** [comment]
#3 

i guess it's not the first time :)

is it possible to fix that? 
thanks

**Comment by sergeyd63** [comment]
@p-try 

another potential fail point: there is a call for `stack[3]` at line 104

**Comment by saghul** [comment]
That's fine because there is a explicit check for stack[3] before that.

**Comment by sergeyd63** [comment]
@saghul  why did you close this issue?

1. the issue is not only with `stack[3]` - the issue is with crash on `stack[2].indexOf` because stack[2] is undefined
2. the call for `stack[3]` is outside of the "explicit check". there is no return or else in case stack[3] is undefined
![image](https://user-images.githubusercontent.com/4738739/100237829-71748f80-2efd-11eb-9e52-ad6d429c6536.png)

**Comment by saghul** [comment]
The PR landed (#9), which fixes the previous issue, and I made a new release with it. Did I miss anything?

**Comment by sergeyd63** [comment]
@saghul  nm :)

thanks. 
it's still early for me

**Comment by saghul** [comment]
No worries!

**Comment by sergeyd63** [comment]
@saghul  thanks again 
and sorry for the mix up 👍 

can that commit be added to lib-jitsi-meet?
it pulls an older commit of the logger
`"jitsi-meet-logger": "github:jitsi/jitsi-meet-logger#5ec92357570dc8f0b7ffc1528820721c84c6af8b"`

**Comment by saghul** [comment]
Yep, I have a PR open already.
